### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by universeroc** [vercel/nextjs-subscription-payments#215]
This is the latest code, I have compile issue local, so I want to deploy to vercel to see what's the version of typescript and etc. But it sucks :( lots of errors during building.

```
[17:00:02.659] Running build in Washington, D.C., USA (East) – iad1
[17:00:02.723] Cloning github.com/universeroc/nextjs-subscription-payments (Branch: main, Commit: 17a4324)
[17:00:02.730] Skipping build cache, deployment was triggered without cache.
[17:00:03.434] Cloning completed: 710.187ms
[17:00:03.627] Running "vercel build"
[17:00:04.159] Vercel CLI 31.0.2
[17:00:04.466] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8...
[17:00:04.488] Installing dependencies...
[17:00:05.084] Lockfile is up to date, resolution step is skipped
[17:00:05.115] Progress: resolved 1, reused 0, downloaded 0, added 0
[17:00:05.212] Packages: +454
[17:00:05.213] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[17:00:05.601] Packages are hard linked from the content-addressable store to the virtual store.
[17:00:05.601]   Content-addressable store is at: /vercel/.local/share/pnpm/store/v3
[17:00:05.601]   Virtual store is at:             node_modules/.pnpm
[17:00:06.124] Progress: resolved 454, reused 0, downloaded 26, added 22
[17:00:07.127] Progress: resolved 454, reused 0, downloaded 74, added 69
[17:00:08.137] Progress: resolved 454, reused 0, downloaded 159, added 155
[17:00:09.142] Progress: resolved 454, reused 0, downloaded 270, added 268
[17:00:10.144] Progress: resolved 454, reused 0, downloaded 375, added 369
[17:00:11.144] Progress: resolved 454, reused 0, downloaded 444, added 444
[17:00:12.144] Progress: resolved 454, reused 0, downloaded 450, added 450
[17:00:13.144] Progress: resolved 454, reused 0, downloaded 451, added 451
[17:00:14.149] Progress: resolved 454, reused 0, downloaded 452, added 452
[17:00:15.149] Progress: resolved 454, reused 0, downloaded 454, added 452
[17:00:16.090]  WARN  Failed to create bin at /vercel/path0/node_modules/.pnpm/supabase@1.64.8/node_modules/supabase/node_modules/.bin/supabase. The source file at /vercel/path0/node_modules/.pnpm/supabase@1.64.8/node_modules/supabase/bin/supabase does not exist.
[17:00:16.091] .../es5-ext@0.10.62/node_modules/es5-ext postinstall$  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
[17:00:16.114] .../node_modules/supabase postinstall$ node scripts/postinstall.js
[17:00:16.135] .../node_modules/bufferutil install$ node-gyp-build
[17:00:16.157] Progress: resolved 454, reused 0, downloaded 454, added 454, done
[17:00:16.159] .../node_modules/utf-8-validate install$ node-gyp-build
[17:00:16.195] .../es5-ext@0.10.62/node_modules/es5-ext postinstall: Done
[17:00:16.334] .../node_modules/supabase postinstall: Downloading https://github.com/supabase/cli/releases/download/v1.64.8/supabase_linux_amd64.tar.gz
[17:00:16.359] .../node_modules/utf-8-validate install: Done
[17:00:16.366] .../node_modules/bufferutil install: Done
[17:00:16.757] .../node_modules/supabase postinstall: Installed Supabase CLI successfully
[17:00:16.762] .../node_modules/supabase postinstall: Done
[17:00:17.583] 
[17:00:17.584] dependencies:
[17:00:17.584] + @stripe/stripe-js 1.54.0
[17:00:17.584] + @supabase/auth-helpers-nextjs 0.7.0
[17:00:17.584] + @supabase/auth-ui-react 0.4.2
[17:00:17.584] + @supabase/auth-ui-shared 0.1.6
[17:00:17.584] + @supabase/supabase-js 2.24.0
[17:00:17.584] + classnames 2.3.2
[17:00:17.584] + next 13.4.3
[17:00:17.584] + react 18.2.0
[17:00:17.584] + react-dom 18.2.0
[17:00:17.584] + react-merge-refs 2.0.2
[17:00:17.584] + stripe 12.7.0
[17:00:17.584] + tailwindcss 3.3.2
[17:00:17.584] 
[17:00:17.585] devDependencies:
[17:00:17.585] + @ianvs/prettier-plugin-sort-imports 3.7.2
[17:00:17.585] + @types/node 20.2.5
[17:00:17.585] + @types/react 18.2.7
[17:00:17.585] + autoprefixer 10.4.14
[17:00:17.585] + eslint 8.41.0
[17:00:17.585] + eslint-config-next 13.4.3
[17:00:17.585] + eslint-config-prettier 8.8.0
[17:00:17.585] + eslint-plugin-react 7.32.2
[17:00:17.585] + eslint-plugin-tailwindcss 3.12.0
[17:00:17.585] + postcss 8.4.24
[17:00:17.585] + prettier 2.8.8
[17:00:17.585] + prettier-plugin-tailwindcss 0.3.0
[17:00:17.585] + supabase 1.64.8
[17:00:17.585] + typescript 5.0.4
[17:00:17.585] 
[17:00:18.032] Done in 13.4s
[17:00:18.064] Detected Next.js version: 13.4.3
[17:00:18.072] Running "pnpm run build"
[17:00:18.605] 
[17:00:18.605] > nextjs-subscription-payments@0.0.0 build /vercel/path0
[17:00:18.605] > next build
[17:00:18.606] 
[17:00:19.049] - warn You have enabled experimental feature (serverActions) in next.config.js.
[17:00:19.050] - warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
[17:00:19.050] 
[17:00:19.068] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[17:00:19.068] This information is used to shape Next.js' roadmap and prioritize features.
[17:00:19.068] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[17:00:19.068] https://nextjs.org/telemetry
[17:00:19.068] 
[17:00:19.170] - info Creating an optimized production build...
[17:00:35.203] - warn Compiled with warnings
[17:00:35.203] 
[17:00:35.204] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js
[17:00:35.204] Module not found: Can't resolve 'encoding' in '/vercel/path0/node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib'
[17:00:35.204] 
[17:00:35.204] Import trace for requested module:
[17:00:35.204] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js
[17:00:35.204] ./node_modules/.pnpm/cross-fetch@3.1.6/node_modules/cross-fetch/dist/node-ponyfill.js
[17:00:35.204] ./node_modules/.pnpm/@supabase+supabase-js@2.24.0/node_modules/@supabase/supabase-js/dist/main/lib/fetch.js
[17:00:35.205] ./node_modules/.pnpm/@supabase+supabase-js@2.24.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js
[17:00:35.207] ./node_modules/.pnpm/@supabase+supabase-js@2.24.0/node_modules/@supabase/supabase-js/dist/main/index.js
[17:00:35.207] ./utils/supabase-admin.ts
[17:00:35.207] ./app/api/create-portal-link/route.ts
[17:00:35.207] 
[17:00:35.207] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js
[17:00:35.207] Module not found: Can't resolve 'encoding' in '/vercel/path0/node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib'
[17:00:35.207] 
[17:00:35.207] Import trace for requested module:
[17:00:35.208] ./node_modules/.pnpm/node-fetch@2.6.11/node_modules/node-fetch/lib/index.js
[17:00:35.208] ./node_modules/.pnpm/cross-fetch@3.1.6/node_modules/cross-fetch/dist/node-ponyfill.js
[17:00:35.208] ./node_modules/.pnpm/@supabase+supabase-js@2.24.0/node_modules/@supabase/supabase-js/dist/main/lib/fetch.js
[17:00:35.208] ./node_modules/.pnpm/@supabase+supabase-js@2.24.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js
[17:00:35.208] ./node_modules/.pnpm/@supabase+supabase-js@2.24.0/node_modules/@supabase/supabase-js/dist/main/index.js
[17:00:35.208] ./node_modules/.pnpm/@supabase+auth-helpers-shared@0.4.0_@supabase+supabase-js@2.24.0/node_modules/@supabase/auth-helpers-shared/dist/index.js
[17:00:35.208] ./node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.7.0_@supabase+supabase-js@2.24.0/node_modules/@supabase/auth-helpers-nextjs/dist/index.js
[17:00:35.208] ./app/supabase-provider.tsx
[17:00:35.208] 
[17:00:35.212] - info Linting and checking validity of types...
[17:00:39.297] - info Collecting page data...
[17:00:39.692] Error: supabaseUrl is required.
[17:00:39.693]     at new SupabaseClient (/vercel/path0/.next/server/chunks/213.js:7385:33)
[17:00:39.693]     at createClient (/vercel/path0/.next/server/chunks/213.js:7615:12)
[17:00:39.693]     at 11325 (/vercel/path0/.next/server/chunks/325.js:93:90)
[17:00:39.693]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[17:00:39.693]     at 79780 (/vercel/path0/.next/server/app/api/create-checkout-session/route.js:184:22)
[17:00:39.693]     at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:25:43)
[17:00:39.693]     at __webpack_exec__ (/vercel/path0/.next/server/app/api/create-checkout-session/route.js:327:39)
[17:00:39.693]     at /vercel/path0/.next/server/app/api/create-checkout-session/route.js:328:90
[17:00:39.693]     at __webpack_require__.X (/vercel/path0/.next/server/webpack-runtime.js:138:21)
[17:00:39.693]     at /vercel/path0/.next/server/app/api/create-checkout-session/route.js:328:47
[17:00:39.696] 
[17:00:39.696] > Build error occurred
[17:00:39.698] Error: Failed to collect page data for /api/create-checkout-session
[17:00:39.699]     at /vercel/path0/node_modules/.pnpm/next@13.4.3_@babel+core@7.22.1_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1152:15
[17:00:39.699]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[17:00:39.699]   type: 'Error'
[17:00:39.699] }
[17:00:39.736]  ELIFECYCLE  Command failed with exit code 1.
[17:00:39.761] Error: Command "pnpm run build" exited with 1
```

**Comment by thorwebdev** [comment]
Please use the Deploy Button in the GitHub README, otherwise you will need to set the required ENV variables yourself manually. 

The error that aborts the build here is 

Error: supabaseUrl is required.
