### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by hridaya423** [vercel/nextjs-subscription-payments#341]
```

Error: supabaseUrl is required.
--
16:49:50.780 | at new ag (/vercel/path0/.next/server/chunks/856.js:1:109603)
16:49:50.780 | at aw (/vercel/path0/.next/server/chunks/856.js:1:112826)
16:49:50.781 | at 37446 (/vercel/path0/.next/server/app/api/webhooks/route.js:1:72564)
16:49:50.781 | at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
16:49:50.781 | at r (/vercel/path0/.next/server/app/api/webhooks/route.js:1:112889)
16:49:50.781 | at /vercel/path0/.next/server/app/api/webhooks/route.js:1:112916
16:49:50.782 | at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1181)
16:49:50.784 | at /vercel/path0/.next/server/app/api/webhooks/route.js:1:112902
16:49:50.784 | at Object.<anonymous> (/vercel/path0/.next/server/app/api/webhooks/route.js:1:112944)
16:49:50.784 | at Module._compile (node:internal/modules/cjs/loader:1358:14)
16:49:50.789 |  
16:49:50.789 | > Build error occurred
16:49:50.791 | Error: Failed to collect page data for /api/webhooks
16:49:50.791 | at /vercel/path0/node_modules/.pnpm/next@14.1.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1258:15
16:49:50.791 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
16:49:50.791 | type: 'Error'
16:49:50.791 | }
16:49:50.807 | ELIFECYCLE  Command failed with exit code 1.
16:49:50.826 | Error: Command "pnpm run build" exited with 1

```

I have used the deploy button from github, followed all steps, as soon as i change anything in the github repo it fails, didnt touch the api/webhooks folder, just some footer changes and removing readme, and public files related to it. It worked before i changed anything.

**Comment by hridaya423** [comment]
anyone else with this error, supabase key, url are production only whereas the deployment was in preview therefore failure

**Comment by thiagodebastos** [comment]
I am facing the same issue. I will work on this again tomorrow morning and will get back to you with a fix if I find it.

**Comment by dan-the-dev** [comment]
> > anyone else with this error, supabase key, url are production only whereas the deployment was in preview therefore failure
> 
> The solution seems to be to create separate Supabase projects for staging and production environments, and use the relevant keys and url's from the staging environment.

Ok but how can I sync that? I was hoping to not create a testing Supabase project since I can use local to develop. If I have to support preview on Vercel, is there a way to sync 2 project?

**Comment by paulinaboro** [comment]
I have created 2 environments ( DEV and PROD ) . I have 2 Supabase projects DEV & PROD and working on 2 github branches main ( PROD ) and DEV ( dev ).


I still encounter the same error:

```
Error: supabaseUrl is required.
    at new ay (/vercel/path0/.next/server/chunks/286.js:1:111494)
    at ab (/vercel/path0/.next/server/chunks/286.js:1:114738)
    at 91819 (/vercel/path0/.next/server/app/api/webhooks/route.js:1:77116)
    at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
    at r (/vercel/path0/.next/server/app/api/webhooks/route.js:1:117797)
    at /vercel/path0/.next/server/app/api/webhooks/route.js:1:117828
    at t.X (/vercel/path0/.next/server/webpack-runtime.js:1:1191)
    at /vercel/path0/.next/server/app/api/webhooks/route.js:1:117810
    at Object.<anonymous> (/vercel/path0/.next/server/app/api/webhooks/route.js:1:117856)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
> Build error occurred
Error: Failed to collect page data for /api/webhooks
    at /vercel/path0/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm run build" exited with 1

```
