### ISSUE TITLE
Reset password fails  - "invalid request: both auth code and code verifier should be non-empty"

### ISSUE THREAD

**Issue by BlakeQG** [vercel/nextjs-subscription-payments#371]
I try to explore the "reset the password" after deployment, unfortunately it doesn't work. 

Detail: I did get the reset password email, then clicked the link, yet the update_password page seemed crashing.

Took a look at the log, the error is in the `/auth/reset_password`

```
⨯ eG [AuthApiError]: invalid request: both auth code and code verifier should be non-empty
    at e5 (/var/task/.next/server/chunks/286.js:1:69374)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ae (/var/task/.next/server/chunks/286.js:1:70373)
    at async e7 (/var/task/.next/server/chunks/286.js:1:70029)
    at async ag._exchangeCodeForSession (/var/task/.next/server/chunks/286.js:1:84836)
    at async /var/task/.next/server/chunks/286.js:1:90526 {
  __isAuthError: true,
  status: 400,
  code: 'validation_failed'
}
```

Any suggestion? Thanks

**Comment by BlakeQG** [comment]
I might figure out the issue.  In the `SignIn` component, it tries to get the user with `supabase.auth.getUser();`. But since the user forgot its password and not sign in, this is always null, so always redicts to `'/signin'`.

```
  const {
    data: { user }
  } = await supabase.auth.getUser();

  if (user && viewProp !== 'update_password') {
    return redirect('/');
  } else if (!user && viewProp === 'update_password') {
    return redirect('/signin');
  }

```

**Comment by BlakeQG** [comment]
I figured it out. During the vercel deployment there are multiple URLs.  I used one to click the "forgot password", yet the reset email site url points to another one, so resulting the mis-match..
