### ISSUE TITLE
The build fails when one try to deploy

### ISSUE THREAD

**Issue by blazestudios23** [vercel/nextjs-subscription-payments#69]
Hello I tried to test this, but the build fails when I try to deploy. 

```
An invalid response was received from the upstream server
22:50:31.844
Unhandled error during request: {
22:50:31.844
  message: 'An invalid response was received from the upstream server'
22:50:31.844
}
22:50:31.844
22:50:31.844
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
22:50:31.844
undefined
22:50:31.845
info  - Generating static pages (5/5)
22:50:31.845
22:50:31.845
> Build error occurred
22:50:31.847
Error: Export encountered errors on following paths:
22:50:31.847
	/
22:50:31.847
    at exportApp (/vercel/path0/node_modules/next/dist/export/index.js:30:1103)
22:50:31.847
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
22:50:31.847
    at async /vercel/path0/node_modules/next/dist/build/index.js:39:69
22:50:31.847
    at async /vercel/path0/node_modules/next/dist/build/tracer.js:1:525
22:50:31.886
error Command failed with exit code 1.
22:50:31.886
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
22:50:31.904
Error: Command "yarn run build" exited with 1

```

I'm honestly just trying to figure out how to integrate all three of these devices together on an existing Next project on Vercel, so maybe just show me how to add them to my project.

**Comment by CR1AT0RS** [comment]
Same error for me when I try to connect Stripe

**Comment by dbredvick** [comment]
Hi @blazestudios23 & @CR1AT0RS, we updated the README to include manual steps to configure Stripe. 

Please follow those and let me know if you have any trouble. Thanks!
