### ISSUE TITLE
Deploy failed

### ISSUE THREAD

**Issue by ehoch** [vercel/nextjs-subscription-payments#89]
Used the deploy button from the Github readme, set up supabase, etc and got:

```
08:53:11.177 | Analyzing source code...
08:53:12.472 | Installing build runtime...
08:53:14.674 | Build runtime installed: 2.202s
08:53:17.285 | Looking up build cache...
08:53:17.415 | Build Cache not found
08:53:18.766 | Installing dependencies...
08:53:19.080 | yarn install v1.22.17
08:53:19.167 | [1/4] Resolving packages...
08:53:19.550 | [2/4] Fetching packages...
08:53:30.868 | [3/4] Linking dependencies...
08:53:30.872 | warning " > tailwindcss@2.0.2" has unmet peer dependency "autoprefixer@^10.0.2".
08:53:35.432 | [4/4] Building fresh packages...
08:53:38.080 | Done in 19.01s.
08:53:38.101 | Detected Next.js version: 10.0.5
08:53:38.104 | Running "yarn run build"
08:53:38.447 | yarn run v1.22.17
08:53:38.487 | $ next build
08:53:39.321 | Browserslist: caniuse-lite is outdated. Please run:
08:53:39.322 | npx browserslist@latest --update-db
08:53:39.467 | info - Creating an optimized production build...
08:53:39.498 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
08:53:39.499 | This information is used to shape Next.js' roadmap and prioritize features.
08:53:39.499 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
08:53:39.499 | https://nextjs.org/telemetry
08:53:39.800 | Browserslist: caniuse-lite is outdated. Please run:
08:53:39.801 | npx browserslist@latest --update-db
08:53:39.801 | Why you should do it regularly:
08:53:39.801 | https://github.com/browserslist/browserslist#browsers-data-updating
08:53:40.904 | Browserslist: caniuse-lite is outdated. Please run:
08:53:40.905 | npx browserslist@latest --update-db
08:53:40.905 | Why you should do it regularly:
08:53:40.906 | https://github.com/browserslist/browserslist#browsers-data-updating
08:54:02.348 | info - Compiled successfully
08:54:02.350 | info - Collecting page data...
08:54:02.894 | info - Generating static pages (0/5)
08:54:03.232 | info - Generating static pages (1/5)
08:54:03.311 | info - Generating static pages (2/5)
08:54:03.343 | info - Generating static pages (3/5)
08:54:03.555 | Could not find a relationship between products and prices in the schema cache
08:54:03.558 | Unhandled error during request: {
08:54:03.561 | hint: 'If a new foreign key between these entities was created in the database, try reloading the schema cache.',
08:54:03.561 | message: 'Could not find a relationship between products and prices in the schema cache'
08:54:03.561 | }
08:54:03.562 | Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
08:54:03.562 | undefined
08:54:03.562 | > Build error occurred
08:54:03.562 | info - Generating static pages (5/5)
08:54:03.565 | Error: Export encountered errors on following paths:
08:54:03.565 | /
08:54:03.566 | at exportApp (/vercel/path0/node_modules/next/dist/export/index.js:30:1103)
08:54:03.567 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
08:54:03.567 | at async /vercel/path0/node_modules/next/dist/build/index.js:39:69
08:54:03.567 | at async /vercel/path0/node_modules/next/dist/build/tracer.js:1:525
08:54:03.606 | error Command failed with exit code 1.
08:54:03.606 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
08:54:03.628 | Error: Command "yarn run build" exited with 1
```

**Comment by ehoch** [comment]
Looks like my supabase database schema failed to be updated. All good now!

**Comment by SaamuelBy** [comment]
Hi, how did you fixed it ?

**Comment by JakeGinnivan** [comment]
You need to run schema.sql against your supabase database, then deploy

**Comment by Yiannistaos** [comment]
> 

Many thanks!
