### ISSUE TITLE
Cannot read property 'currency' of undefined

### ISSUE THREAD

**Issue by vivacoda** [vercel/nextjs-subscription-payments#90]
Hello I am using Euro  currency and looks like it's problem.
Any idea how to manage it

Best regards

```
Unhandled error during request: TypeError: Cannot read property 'currency' of undefined
    at /vercel/path0/.next/serverless/pages/index.js:1820:29
    at Array.map (<anonymous>)
    at Pricing (/vercel/path0/.next/serverless/pages/index.js:1814:28)
    at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/vercel/path0/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (/vercel/path0/.next/serverless/pages/index.js:2108:19)
Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
TypeError: Cannot read property 'currency' of undefined
    at /vercel/path0/.next/serverless/pages/index.js:1820:29
    at Array.map (<anonymous>)
    at Pricing (/vercel/path0/.next/serverless/pages/index.js:1814:28)
    at d (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at a.b.render (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/vercel/path0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/vercel/path0/node_modules/next/dist/next-server/server/render.js:54:851)
    at Function.getInitialProps (/vercel/path0/.next/serverless/pages/index.js:2108:19)
> Build error occurred
info  - Generating static pages (5/5)
Error: Export encountered errors on following paths:
	/
    at exportApp (/vercel/path0/node_modules/next/dist/export/index.js:30:1103)
    at async /vercel/path0/node_modules/next/dist/build/index.js:39:69
    at async /vercel/path0/node_modules/next/dist/build/tracer.js:1:525
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
```

**Comment by vivacoda** [comment]
i dig a bit more and check related issues 
my products are synchronizing in supabase succesfuly.
![Screen Shot 2021-11-14 at 09 40 40](https://user-images.githubusercontent.com/75243836/141665392-99772614-30af-4369-a3d9-b7b606b8932a.png)
I double check the stripe setup on your readme looks Ok.
I cant find my mistake.
Regards

**Comment by thorwebdev** [comment]
Hey @vivacoda can you check your prices table?
![image](https://user-images.githubusercontent.com/5748289/141667849-43fd94c4-e71d-4999-9325-61429998243d.png)

**Comment by vivacoda** [comment]
I also check looks Ok. Maybe i miss something.

<img width="1411" alt="Screen Shot 2021-11-14 at 13 15 04" src="https://user-images.githubusercontent.com/75243836/141669990-8510f50e-315e-422c-86a8-d16ffa4c8f85.png">
[products_rows.csv](https://github.com/vercel/nextjs-subscription-payments/files/7533261/products_rows.csv)
[prices_rows.csv](https://github.com/vercel/nextjs-subscription-payments/files/7533262/prices_rows.csv)
.

**Comment by thorwebdev** [comment]
Can you check your schema for the prices table (click the little arrow next to `prices` and select `edit table`)? Maybe the relationship between products and prices isn't correctly set up?

![image](https://user-images.githubusercontent.com/5748289/141707952-d291ba7d-366f-40e6-8eb1-4db4f6718a06.png)

**Comment by vivacoda** [comment]
Thanks i am really grateful for your help
<img width="670" alt="Screen Shot 2564-11-15 at 08 51 56" src="https://user-images.githubusercontent.com/75243836/141710036-ea97b8e6-1d40-4b94-84ad-9ea91f1a1b53.png">

**Comment by thorwebdev** [comment]
Okay, that looks all fine. Have you tried redeploying your page? 

The products and prices are fetched at build time and then saved statically (`getStaticProps`): https://github.com/vercel/nextjs-subscription-payments/blob/main/pages/index.tsx#L14 so maybe they prices were just not inserted yet when your build was running?

**Comment by vivacoda** [comment]
Same Error. 
I will delete the supabase and github and clone again.

**Comment by vivacoda** [comment]
DEV mode Fresh clone
![Screen Shot 2564-11-15 at 11 34 33](https://user-images.githubusercontent.com/75243836/141723074-eee60cca-a3fb-49a1-be7b-dc37782109dc.png)
I give UP
i try with the webhook on the vercel subdomaine and with my domain 
When it's build it's not affect the sync
when it's Sync build error

**Comment by vivacoda** [comment]
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[object Object]
info  - Generating static pages (6/6)
> Build error occurred
Error: Export encountered errors on following paths:
	/
    at /vercel/path0/node_modules/next/dist/export/index.js:493:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:74:20)
    at async /vercel/path0/node_modules/next/dist/build/index.js:962:17
    at async /vercel/path0/node_modules/next/dist/build/index.js:836:13
    at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:74:20)
    at async Object.build [as default] (/vercel/path0/node_modules/next/dist/build/index.js:82:25)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1

**Comment by vivacoda** [comment]
On my own server i got
```
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[    ] info  - Generating static pages (0/6)Could not find a relationship between products and prices in the schema cache

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
[object Object]
info  - Generating static pages (6/6)

> Build error occurred
Error: Export encountered errors on following paths:
	/
    at /var/www/viva-sub-fr/node_modules/next/dist/export/index.js:493:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Span.traceAsyncFn (/var/www/viva-sub-fr/node_modules/next/dist/trace/trace.js:74:20)
    at async /var/www/viva-sub-fr/node_modules/next/dist/build/index.js:962:17
    at async Span.traceAsyncFn (/var/www/viva-sub-fr/node_modules/next/dist/trace/trace.js:74:20)
    at async /var/www/viva-sub-fr/node_modules/next/dist/build/index.js:836:13
    at async Span.traceAsyncFn (/var/www/viva-sub-fr/node_modules/next/dist/trace/trace.js:74:20)
    at async Object.build [as default] (/var/www/viva-sub-fr/node_modules/next/dist/build/index.js:82:25)
error Command failed with exit code 1.
```
All my credential are OK 
new DB on supabase and fresh clone.

**Comment by vivacoda** [comment]
![Screen Shot 2564-11-17 at 07 48 47](https://user-images.githubusercontent.com/75243836/142089175-8badc6cc-d118-4589-b09b-2238fd726a7b.png)
Still not working With the deploy BTN on your repo.

**Comment by thorwebdev** [comment]
Very sorry about this. Can you try this (https://github.com/vercel/nextjs-subscription-payments/issues/88#issuecomment-962549480) while we're looking at the Vercel deploy integration?

**Comment by vivacoda** [comment]
:) 

> Very sorry about this. Can you try this ([#88 (comment)](https://github.com/vercel/nextjs-subscription-payments/issues/88#issuecomment-962549480)) while we're looking at the Vercel deploy integration?

I did Thanks now it's build without falling 
i add all the env variable.
Supabase empty table No sync. Hope Supabase, NextJS and vercel will sync together before thanksgiving :)
Stripe  sync

```
reporting.report_type.updated
Resend
More options
Response
200 OK

{
  "received": true
}
```

![Screen Shot 2564-11-18 at 09 21 43](https://user-images.githubusercontent.com/75243836/142340550-cb1bdf27-273e-4e9c-b238-f578d1c904ef.png)

**Comment by thorwebdev** [comment]
You will need to make sure that you'r project is deployed and your webhook settings are configured correctly before creating the products in Stripe. Try creating a new product in Stripe and see if it syncs. If not, post the Stripe webhook dashboard logs and the vercel function error logs here.

**Comment by thorwebdev** [comment]
Closing due to inaction.
